import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FDF3F6',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#FFE082',
    marginTop: 20,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButtonText: {
    color: '#1E88E5',
    fontSize: 16,
    marginLeft: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#E91E63',
    flex: 1,
    textAlign: 'center',
  },
  adicionarButton: {
    padding: 8,
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listaEducadoras: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#666',
    marginTop: 32,
  },
  educadoraItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 10,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  educadoraInfo: {
    flex: 1,
    marginRight: 16,
  },
  educadoraNome: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E88E5',
  },
  educadoraTipo: {
    fontSize: 14,
    color: '#E91E63',
    marginTop: 4,
  },
  educadoraEmail: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  removerButton: {
    padding: 8,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  modalContent: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 24,
    textAlign: 'center',
    color: '#E91E63',
  },
  inputContainer: {
    marginBottom: 16,
    flexDirection: 'row', 
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#FFE082',
    paddingBottom: 4,
  },
  label: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  input: {
    flex: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#333',
  },
  passwordToggle: {
    padding: 5,
    marginLeft: 10,
  },
  tipoContainer: {
    marginBottom: 16,
  },
  radioContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioCircle: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#1E88E5',
    marginRight: 8,
  },
  selectedRadio: {
    backgroundColor: '#1E88E5',
  },
  radioLabel: {
    fontSize: 16,
    color: '#333',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  modalCancelarButton: {
    flex: 1,
    marginRight: 10,
    padding: 14,
    backgroundColor: '#FCE4EC',
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCancelarButtonText: {
    color: '#E91E63',
    fontSize: 16,
    fontWeight: '500',
  },
  modalSalvarButton: {
    flex: 1,
    marginLeft: 10,
    padding: 14,
    backgroundColor: '#1E88E5',
    borderRadius: 8,
    alignItems: 'center',
  },
  modalSalvarButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  listaTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#E91E63',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
});